//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore_Chitaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID_Employees { get; set; }
        public Nullable<int> Id_Role { get; set; }
        public string FIO { get; set; }
        public string Login { get; set; }
        public string Pasword { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
