//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore_Chitaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Status
    {
        public Order_Status()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Status_ID { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
