//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore_Chitaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int Order_ID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> PickupPoint_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> PickupCode { get; set; }
        public Nullable<int> Status_ID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual Order_Status Order_Status { get; set; }
        public virtual Point Point { get; set; }
    }
}
