//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore_Chitaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int Product_ID { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Price { get; set; }
        public string Supplier { get; set; }
        public Nullable<int> Manufacturer_ID { get; set; }
        public string Category { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Stock_Quantity { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public bool is_discount => (Discount ?? 0) > 15;
        public bool is_on_sale => (Discount ?? 0) > 0;

        public decimal? price_discount
        {
            get
            {
                if (Discount == null || Discount == 0) return Price;
                return Price - (Price * Discount.Value / 100.0m);
            }
        }

        public bool is_quantity => (Stock_Quantity ?? 0) <= 0;

        public string PhotoPath
        {
            get
            {
                const string placeholder =
                    @"Resources\picture.png";

                if (string.IsNullOrWhiteSpace(Photo))
                    return placeholder;

                if (System.IO.File.Exists(Photo))
                    return Photo;

                string imagesPath = System.IO.Path.Combine(
                    AppDomain.CurrentDomain.BaseDirectory, "Images", Photo);

                if (System.IO.File.Exists(imagesPath))
                    return imagesPath;

                return placeholder;
            }
        }
    }
}
